# Generated by Django 3.0.2 on 2020-03-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_category', models.CharField(choices=[('Electronic', 'electronics'), ('Sport', 'sports'), ('Kitchen', 'kitchens'), ('Men', 'mens')], max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('product_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_on', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Placed', 'placed'), ('Out For Delivery', 'out for delivery'), ('Delivered', 'delivered')], max_length=20)),
                ('order_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dennis.Products')),
                ('placed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dennis.Customer')),
            ],
        ),
    ]
